---
title: "IBM HR Analytics Employee Attrition & Performance"
author: "Awesome Me"
date: "2023-05-14"
link-citations: true
output: html_document
---

### IBM HR Analytics Employee Attrition & Performance
#### https://www.kaggle.com/datasets/pavansubhasht/ibm-hr-analytics-attrition-dataset/code



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## install h2o
<!-- ############################### worked solution ########################## -->
```{r}

install.packages("h2o", type="source", repos="https://h2o-release.s3.amazonaws.com/h2o/master/3978/R")

```

## install h2o
```{r}

# installing H2O’s R package from CRAN
install.packages("h2o", dependencies = T)

```


```{r}
# remove any previously installed H2O packages for R.
if ("package:h2o" %in% search()) { detach("package:h2o", unload=TRUE) }

if ("h2o" %in% rownames(installed.packages())) { remove.packages("h2o") }

# download packages that H2O depends on.
# pkgs <- c("RCurl","jsonlite")
# for (pkg in pkgs) {
#   if (! (pkg %in% rownames(installed.packages()))) { install.packages(pkg) }
# }

if (! ("methods" %in% rownames(installed.packages()))) { install.packages("methods") }
if (! ("statmod" %in% rownames(installed.packages()))) { install.packages("statmod") }
if (! ("stats" %in% rownames(installed.packages()))) { install.packages("stats") }
if (! ("graphics" %in% rownames(installed.packages()))) { install.packages("graphics") }
if (! ("RCurl" %in% rownames(installed.packages()))) { install.packages("RCurl") }
if (! ("jsonlite" %in% rownames(installed.packages()))) { install.packages("jsonlite") }
if (! ("tools" %in% rownames(installed.packages()))) { install.packages("tools") }
if (! ("utils" %in% rownames(installed.packages()))) { install.packages("utils") }

# download and install the H2O package for R
install.packages("h2o", type="source", repos=(c("https://cran.rstudio.com/bin/windows/contrib/4.2/h2o_3.40.0.1.zip")))
# install.packages("h2o", type="source", repos=(c("http://h2o-release.s3.amazonaws.com/h2o/rel-zz_kurka/4/index.html")))
# install.packages("h2o", type="source", repos=(c("http://h2o-release.s3.amazonaws.com/h2o/latest_stable_R")))
# install.packages("h2o", type="source", repos=(c("h2o-release.s3.amazonaws.com/h2o/rel-zz_kurka/4/h2o-3.40.0.4.zip")))

```


## or install h2o manually
### https://discuss.analyticsvidhya.com/t/package-h20-is-not-available-for-r-version-3-2-3/18890
```{r}

install.packages("h2o", "E:/h2o/h2o_3.40.0.1.zip", repos = NULL, type='source')

```

## 
```{r}
install.packages("Rtools")

```


## load packages
```{r}
if(!require("pacman")) install.packages("pacman")
pacman::p_load(
 h2o, # initialize H2O 
 here
)

# library(h2o) # initialize H2O 
h2o::h2o.init()

```

### set seed for reproducibility
```{r}
# implement or use packages such as bruceR or liver
min_max <- function(x) 
{
  return ((x - min(x)) / (max(x) - min(x)))
}

```
